#!/usr/bin/env python3
"""
build.py -- build the shipped single file from the template (manual 7.7/12).

  - says loudly in the generated file that it is generated and which file to
    edit (the template's own banner does this);
  - inlines the asset JSON inside a script element of a NON-EXECUTABLE type,
    escaping the sequence "</" so the payload cannot break out;
  - RE-PARSES the escaped text to prove the escaping held, and FAILS THE BUILD
    if a placeholder was not substituted.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TEMPLATE = os.path.join(ROOT, 'client', 'template.html')
ASSETS = os.path.join(ROOT, 'build', 'assets.json')
OUT = os.path.join(ROOT, 'client', 'gauntlet.html')

BANNER = ('<!-- GENERATED by tools/build.py from web/template.html -- '
          'DO NOT EDIT THIS FILE. Edit the template and rebuild. -->\n')


def main():
    tpl = open(TEMPLATE, encoding='utf-8').read()
    assets = json.load(open(ASSETS, encoding='utf-8'))

    # The player's animation frames, DECODED from the 33-byte sprite records by
    # tools/playersprite.py and gated against the running original (see its
    # docstring).  The draw origin travels with the frames because it is a
    # measurement, not a constant this file gets to choose -- an earlier build
    # hard-coded (-8, 0) here and froze a sampling artefact into the engine.
    frames_path = os.path.join(ROOT, 'build', 'player_frames.json')
    if os.path.exists(frames_path):
        pf = json.load(open(frames_path, encoding='utf-8'))
        assert '_origin' in pf, 'player_frames.json carries no measured origin'
        assets['player_frames'] = pf

    # The MONSTERS' animation frames, decoded from the same 33-byte records by
    # tools/actorframes.py.  The id formula they are indexed by was verified
    # against the id the game itself hands the blitter at $AD13 (512/512).
    actors_path = os.path.join(ROOT, 'build', 'actor_frames.json')
    if os.path.exists(actors_path):
        assets['actor_frames'] = json.load(open(actors_path, encoding='utf-8'))

    # The SHOT records, decoded by tools/shotframes.py from the four sprite
    # banks the game stashes in the shadow screen's unused HUD rows.  Their
    # addresses come from $8DE9..$8DF8's own arithmetic, not the $7B00 table.
    shots_path = os.path.join(ROOT, 'build', 'shot_frames.json')
    if os.path.exists(shots_path):
        sf = json.load(open(shots_path, encoding='utf-8'))
        # four character banks plus the MONSTER tag $90 (which aliases $10 --
        # see tools/shotframes.py's record_addr)
        assert len(sf['banks']) == 5,             'four character shot banks plus the monster tag $90'
        assets['shot_frames'] = sf

    # The HUD's own 8x8 font at $77B0, the field addresses decoded from the
    # printer's own LD DE,$50C9 / SUB 8 / ADD A,$16, and the live counter
    # state -- tools/hudfont.py.  Without it the panel falls back to the
    # static capture and the counters cannot be drawn, so fail loudly.
    hud_path = os.path.join(ROOT, 'build', 'hud_font.json')
    if not os.path.exists(hud_path):
        sys.exit('BUILD FAILED: build/hud_font.json missing '
                 '-- run python tools/hudfont.py')
    # the MESSAGE BANNER's panel art and strings (tools/bannerart.py)
    banner_path = os.path.join(ROOT, 'build', 'banner.json')
    if os.path.exists(banner_path):
        assets['banner'] = json.load(open(banner_path, encoding='utf-8'))
    else:
        print('NOTE: build/banner.json missing -- run tools/bannerart.py; '
              'the message banner will not be drawn')

    # the LEVEL-ENTRY screen's strings and icons (tools/introart.py)
    intro_path = os.path.join(ROOT, 'build', 'intro.json')
    if os.path.exists(intro_path):
        assets['intro'] = json.load(open(intro_path, encoding='utf-8'))
    else:
        print('NOTE: build/intro.json missing -- run tools/introart.py; '
              'the level-entry screen will not be drawn')

    # the RANKED TABLES and their layout (tools/rankgate.py)
    rank_path = os.path.join(ROOT, 'build', 'rank.json')
    if os.path.exists(rank_path):
        assets['rank'] = json.load(open(rank_path, encoding='utf-8'))
    else:
        print('NOTE: build/rank.json missing -- run tools/rankgate.py; '
              'the ranked tables will not be drawn')

    hf = json.load(open(hud_path, encoding='utf-8'))
    # 106, not 96: codes $20..$89, ending exactly at $7B00 where the sprite
    # pointer table begins.  $81..$89 are player 2's VALKYRIE wordmark.
    assert len(hf['font']['glyphs']) == 106, 'the font is 106 glyphs of 8 bytes'
    assets['hud_font'] = hf

    # THE DUNGEONS.  build/packdata.json holds the 307 dungeon records of tape
    # side 2 (125 distinct byte-strings) plus the pack/sub-block index $9175
    # walks; the engine expands them with its own port of $97CB, so what ships
    # is the original's DATA and the original's ALGORITHM rather than a
    # captured picture of one map.  tools/packexport.py asserts the container
    # arithmetic of all 31 packs; tools/levelgate.py + node tools/headless.js
    # then check every one of the 307 against the original's own $8000 buffer.
    packs_path = os.path.join(ROOT, 'build', 'packdata.json')
    if not os.path.exists(packs_path):
        sys.exit('BUILD FAILED: build/packdata.json missing '
                 '-- run python tools/packexport.py')
    pk = json.load(open(packs_path, encoding='utf-8'))
    assert len(pk['packs']) == 31, 'side 2 is 31 blocks'
    assert len(pk['packs'][0]) == 7, 'the $80 pack holds dungeons 1-7'
    assert sum(len(p) for p in pk['packs']) == 307, '307 dungeon records'
    assets['packs'] = pk

    # THE MAP TILES.  A tile is a 33-byte sprite record reached through the
    # $7B00 pointer table with id = ((cell - 1) & $7F) + 1 ($9F7A), and $9AB9
    # rebuilds sixteen of those pointers at every level start from one of five
    # wall banks at $F524 + n*$210, colouring them from $7D9C.  Sampling one
    # dungeon's screen could only ever cover 17 of the 63 values that occur
    # across the 307 dungeons; tools/maptiles.py decodes the records.
    mt_path = os.path.join(ROOT, 'build', 'map_tiles.json')
    if not os.path.exists(mt_path):
        sys.exit('BUILD FAILED: build/map_tiles.json missing '
                 '-- run python tools/maptiles.py')
    mt = json.load(open(mt_path, encoding='utf-8'))
    assert len(mt['banks']) == 5 and len(mt['banks'][0]) == 16
    assert len(mt['schemes']) == 8
    assets['map_tiles'] = mt

    # THE SOUND EFFECTS.  The 18 streams the AY driver plays, straight out of
    # the game's own $73DA table with its offsets resolved -- tools/sfxdata.py,
    # which asserts that the 18 streams tile $73FE..$77AF with zero gaps and
    # that the row counts are the 464 frames tools/soundgate.py's
    # register-level differential compares against the real Z80.  The DECODE
    # is not done here: the engine mirrors $BB35 instead, so the arithmetic
    # (including the eight-bit INC that makes tone byte $FF mean period 0)
    # lives beside the address it came from.
    sfx_path = os.path.join(ROOT, 'build', 'sfx_data.json')
    if not os.path.exists(sfx_path):
        sys.exit('BUILD FAILED: build/sfx_data.json missing '
                 '-- run python tools/sfxdata.py')
    sx = json.load(open(sfx_path, encoding='utf-8'))
    assert len(sx['effects']) == 18, 'the $73DA table is 18 entries'
    assert sum(len(e['rows']) for e in sx['effects']) == 464, \
        'the 18 effects are 464 frames in total'
    assets['sfx'] = sx

    # THE 48K BEEPER -- THE SHIPPED SOUND PATH.  build/beeper_data.json is
    # written by tools/beepdata.py from build/state_48k.pkl, the boot in which
    # block A's own $7FFD paging probe wrote 0 to RAM $FFFD and $BF21 applied
    # its 48K arm; nothing there pokes a branch byte.  It carries the eight
    # tone streams parsed out of $B92B's own CP chain, the seven silent ids,
    # the noise arms, and the two blocking tunes decoded by MEASUREMENT (a
    # hook on $C081/$C0B6 in the relocated player).  beepdata.py asserts the
    # tiling of $B995..$BA00, the 50 records, the even toggle counts and the
    # unreachability of both 256-wraps; re-assert the shape here so a stale
    # file cannot ship.
    beep_path = os.path.join(ROOT, 'build', 'beeper_data.json')
    if not os.path.exists(beep_path):
        sys.exit('BUILD FAILED: build/beeper_data.json missing '
                 '-- run python tools/beepdata.py')
    bp = json.load(open(beep_path, encoding='utf-8'))
    assert len(bp['streams']) == 9, 'nine ids reach a tone stream'
    assert sum(len(r) for r in bp['streams'].values()) == 59, \
        '59 played steps across the nine ids'
    assert len({tuple(map(tuple, r)) for r in bp['streams'].values()}) == 8, \
        'eight DISTINCT streams -- ids 6 and $0F share $B9E5'
    assert sorted(bp['silent']) == [1, 3, 5, 9, 12, 13, 16], \
        'the seven silent ids moved'
    assert len(bp['tunes']['banner']['rows']) == 8 and \
        len(bp['tunes']['level']['rows']) == 23, 'the tune rows moved'
    assets['beeper'] = bp

    # THE FRONT END -- block A.  The loading screen, the title/character
    # screen, block A's own 8x8 font, the three text pages, the picker's
    # tables, the menu box strings, the 48K title tune, and block C's four
    # ranked tables plus the class names and the REWIND prompt.  Extracted by
    # tools/fedata.py straight out of build/image_a.bin and build/image.bin at
    # addresses recovered from a disassembly taken from a known instruction
    # boundary ($C895's inline strings make a plain disassembler lose it).
    fe_path = os.path.join(ROOT, 'build', 'fe_data.json')
    if not os.path.exists(fe_path):
        sys.exit('BUILD FAILED: build/fe_data.json missing '
                 '-- run python tools/fedata.py')
    fe = json.load(open(fe_path, encoding='utf-8'))
    for k in ('loading_screen', 'title_screen', 'font', 'pages', 'picker',
              'boxes', 'tune', 'hiscore', 'class_names', 'rewind'):
        if k not in fe:
            sys.exit(f'BUILD FAILED: fe_data.json has no {k} '
                     f'-- re-run tools/fedata.py')
    # the picker's default cursor IS the menu's default character, and this
    # project has been wrong about that byte for its whole life; assert it
    assert fe['picker']['cursor_default'] == 0, \
        'the character picker no longer defaults to 0 (the WARRIOR)'
    assert fe['picker']['papers'] == [0x10, 0x28, 0x30, 0x20], \
        'the picker quadrant colours moved'
    assert len(fe['hiscore']['tables']) == 4 and \
        all(len(t) == 60 for t in fe['hiscore']['tables']), \
        'the four ranked tables are 60 bytes each'
    assert len(fe['tune']['ch1']) == 103 and len(fe['tune']['ch2']) == 103, \
        'the title tune is 103 played ticks a channel'
    assets['frontend'] = fe

    # THE WIRE (shared/PROTOCOL.md).  The client speaks the relay protocol,
    # and its constants come from the same shared/protocol.json the C++
    # mirrors -- tools/protocheck.py holds that side to it; inlining this
    # side makes JS drift impossible outright.
    proto_path = os.path.join(ROOT, 'shared', 'protocol.json')
    if not os.path.exists(proto_path):
        sys.exit('BUILD FAILED: shared/protocol.json missing')
    assets['protocol'] = json.load(open(proto_path, encoding='utf-8'))

    # The engine reads these unconditionally -- fail the build rather than ship
    # an artifact that throws on load (they are written by tools/extract.py).
    for k in ('pass_ctr', 'hp', 'ghost_damage', 'dirmask', 'deflect',
              'potion_bounty', 'anim_ctr', 'anim_flags'):
        if k not in assets.get('globals', {}):
            sys.exit(f'BUILD FAILED: assets.json has no globals.{k} '
                     f'-- re-run tools/extract.py')

    payload = json.dumps(assets, separators=(',', ':'))
    escaped = payload.replace('</', '<\\/')

    # prove the escaping held, before writing anything
    reparsed = json.loads(escaped.replace('<\\/', '</'))
    assert reparsed == assets, 'escaped payload does not round-trip'
    assert '</' not in escaped, 'payload can still break out of the script tag'

    if '__ASSETS__' not in tpl:
        sys.exit('BUILD FAILED: placeholder __ASSETS__ missing from template')
    out = BANNER + tpl.replace('__ASSETS__', escaped)

    if '__ASSETS__' in out:
        sys.exit('BUILD FAILED: placeholder survived substitution')

    # the inlined payload must still parse out of the BUILT file
    m = re.search(r'<script type="application/json" id="assets">(.*?)</script>',
                  out, re.S)
    if not m:
        sys.exit('BUILD FAILED: cannot find the asset script element in the output')
    json.loads(m.group(1).replace('<\\/', '</'))

    open(OUT, 'w', encoding='utf-8').write(out)
    print(f'payload {len(payload)} bytes -> escaped {len(escaped)} bytes, re-parsed OK')
    tc = assets['tile_closure']
    print(f'map {assets["map"]["w"]}x{assets["map"]["h"]}  '
          f'tiles={len(assets["tiles"])}  '
          f'tile closure {tc["pct"]}% ({tc["same"]}/{tc["total"]})')
    print(f'wrote {OUT} ({len(out)} bytes)')


if __name__ == '__main__':
    main()
