/* relaytest.js -- the relay's empirical gate.  Spawns the built server,
 * speaks real RFC 6455 WebSocket at it (own tiny client -- Node's net +
 * crypto -- so the test controls every frame byte), and plays the whole
 * protocol conversation from shared/PROTOCOL.md: seating, the fresh
 * boot, 100 lockstep passes with byte-order checks, the stall property,
 * fingerprint agreement and desync arbitration, the FULL refusal, a
 * disconnect with zero-substitution, a late join with a 20 KB snapshot
 * forwarded verbatim, and the orphaned-session reset.
 *
 *   node tools/relaytest.js [path\to\gauntlet-relay.exe]
 */
'use strict';
const net = require('net');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const ROOT = path.dirname(__dirname);
const EXE = process.argv[2] ||
  path.join(ROOT, 'server', 'build', 'gauntlet-relay.exe');
const P = require(path.join(ROOT, 'shared', 'protocol.json'));
const PORT = 33913;                       // a test port, not the shipped one
const M = P.msgs, E = P.errors, MODE = P.welcomeModes;

let checks = 0, failures = 0;
const check = (label, got, want) => {
  checks++;
  const g = JSON.stringify(got), w = JSON.stringify(want);
  if (g === w) console.log('  ok    ' + label);
  else { failures++; console.log('  FAIL  ' + label + '  got ' + g + ' want ' + w); }
};
const checkTrue = (label, v, extra) => {
  checks++;
  if (v) console.log('  ok    ' + label);
  else { failures++; console.log('  FAIL  ' + label + (extra ? '  [' + extra + ']' : '')); }
};
const sleep = ms => new Promise(r => setTimeout(r, ms));

/* ---- the WebSocket client lives in tools/wsmini.js, shared with the
   end-to-end test; here it grows the protocol-conversation helpers
   (SEATS and NAMES broadcasts interleave with everything, so expect()
   drops them unless one of them is what the test wants). */
const { Ws: WsBase } = require('./wsmini');
const BCAST = () => [M.SEATS, M.NAMES];
class Ws extends WsBase {
  async expect(type, timeout){
    const m = await this.next(timeout || 3000,
                              BCAST().filter(t => t !== type));
    if (!m) throw new Error('timed out waiting for type ' + type +
                            (this.closed ? ' (closed)' : ''));
    if (m[0] !== type) throw new Error('expected type ' + type + ', got ' + m[0] +
                                       ' [' + m.subarray(0, 12).join(',') + ']');
    return m;
  }
  async silent(ms){
    const m = await this.next(ms, BCAST());
    if (m) throw new Error('expected silence, got type ' + m[0]);
  }
}

/* ---- helpers over the message shapes --------------------------------- */
const u32 = { u32: 0 };
const U32 = v => ({ u32: v });
const rdWelcome = m => ({ seat: m[1], seats: m[2], seed: m.readUInt32LE(3),
                          mode: m[7], pass: m.readUInt32LE(8) });
const rdPass = m => ({ pass: m.readUInt32LE(1), n: m[5],
                       dirs: Array.from(m.subarray(6, 6 + m[5])) });

async function main(){
  console.log('relaytest: ' + EXE);
  const proc = spawn(EXE, ['--port', String(PORT)], { stdio: ['ignore', 'pipe', 'pipe'] });
  let out = '';
  proc.stdout.on('data', d => { out += d.toString(); });
  proc.stderr.on('data', d => { out += d.toString(); });
  const t0 = Date.now();
  while (!/RELAY LISTENING/.test(out)){
    if (Date.now() - t0 > 5000) throw new Error('server never listened: ' + out);
    await sleep(20);
  }
  checkTrue('the server starts and listens', /RELAY LISTENING 33913 seats=2/.test(out));

  try {
    /* ---- the page is the server: plain GET / ------------------------ */
    await new Promise((resolve, reject) => {
      const s = net.connect(PORT, '127.0.0.1');
      let got = Buffer.alloc(0);
      s.on('data', d => { got = Buffer.concat([got, d]); });
      s.on('close', () => {
        const txt = got.toString('latin1');
        checkTrue('GET / serves the game page (200, >100 KB, the built html)',
                  / 200 OK/.test(txt) && got.length > 100000 &&
                  txt.indexOf('GENERATED by tools/build.py') > 0,
                  'len ' + got.length);
        resolve();
      });
      s.on('error', reject);
      s.on('connect', () =>
        s.write('GET / HTTP/1.1\r\nHost: t\r\nConnection: close\r\n\r\n'));
    });

    /* ---- the gzip arm: Accept-Encoding gets the build-time .gz sibling,
       and a REBUILT html with a stale .gz falls back to identity ------- */
    const httpGet = hdrs => new Promise((resolve, reject) => {
      const s = net.connect(PORT, '127.0.0.1');
      let got = Buffer.alloc(0);
      s.on('data', d => { got = Buffer.concat([got, d]); });
      s.on('close', () => {
        const he = got.indexOf('\r\n\r\n');
        resolve({ head: got.subarray(0, he).toString('latin1'),
                  body: got.subarray(he + 4) });
      });
      s.on('error', reject);
      s.on('connect', () =>
        s.write('GET / HTTP/1.1\r\nHost: t\r\n' + hdrs + 'Connection: close\r\n\r\n'));
    });
    const htmlP = path.join(ROOT, 'client', 'gauntlet.html');
    {
      const r = await httpGet('Accept-Encoding: gzip\r\n');
      checkTrue('Accept-Encoding gzip serves the .gz sibling, magic bytes and all',
                / 200 OK/.test(r.head) && /content-encoding: gzip/i.test(r.head) &&
                r.body[0] === 0x1f && r.body[1] === 0x8b &&
                parseInt(/content-length: (\d+)/i.exec(r.head)[1], 10) === r.body.length &&
                r.body.length < 500000,
                'len ' + r.body.length);
      /* _stat64 mtimes are SECOND-granular, so the bumps must clear a
         whole second -- as any real rebuild-vs-stale-sibling gap does */
      const now = new Date(Date.now() + 2000);
      fs.utimesSync(htmlP, now, now);              // html now NEWER than .gz
      const r2 = await httpGet('Accept-Encoding: gzip\r\n');
      checkTrue('a REBUILT html with a stale .gz serves IDENTITY, never a stale page',
                / 200 OK/.test(r2.head) && !/content-encoding/i.test(r2.head) &&
                r2.body.length > 500000);
      const later = new Date(Date.now() + 4000);
      fs.utimesSync(htmlP + '.gz', later, later);  // sibling fresh again
      const r3 = await httpGet('Accept-Encoding: gzip\r\n');
      checkTrue('...and the freshness test is PER REQUEST: a fresh .gz serves again',
                /content-encoding: gzip/i.test(r3.head));
    }

    /* ---- seating and the fresh boot -------------------------------- */
    const c0 = await new Ws().connect(PORT);
    c0.msg(M.HELLO, P.version, 3, Buffer.from('anthony!'));   // the elf, named
    const w0 = rdWelcome(await c0.expect(M.WELCOME));
    check('first client seats at 0, fresh, pass 0',
          [w0.seat, w0.seats, w0.mode, w0.pass], [0, 2, MODE.FRESH, 0]);
    checkTrue('...with a nonzero buildSeed', w0.seed !== 0);
    check('...and CHARS carries his pick, other seats unset',
          Array.from((await c0.expect(M.CHARS)).subarray(1)), [3, 255, 255, 255]);
    check('...and NAMES carries his name SANITIZED (upper, junk to space)',
          (await c0.expect(M.NAMES)).subarray(1).toString(),
          'ANTHONY ' + ' '.repeat(24));

    const c1 = await new Ws().connect(PORT);
    c1.msg(M.HELLO, P.version, 3, Buffer.from('NITRO   '));   // the SAME pick
    const w1 = rdWelcome(await c1.expect(M.WELCOME));
    check('second client seats at 1, still fresh (pass 0)',
          [w1.seat, w1.mode, w1.pass], [1, MODE.FRESH, 0]);
    check('...and both clients share the ONE buildSeed', w1.seed, w0.seed);
    check('a clashing pick is BUMPED past the earlier seat (the engine never fields two of one)',
          Array.from((await c1.expect(M.CHARS)).subarray(1)), [3, 0, 255, 255]);
    check('...and the first client hears the new table too',
          Array.from((await c0.expect(M.CHARS)).subarray(1)), [3, 0, 255, 255]);
    check('NAMES now carries both seats, to both clients',
          [(await c0.expect(M.NAMES)).subarray(1).toString(),
           (await c1.expect(M.NAMES)).subarray(1).toString()],
          ['ANTHONY NITRO   ' + ' '.repeat(16),
           'ANTHONY NITRO   ' + ' '.repeat(16)]);

    /* the wrong protocol version is refused */
    const cv = await new Ws().connect(PORT);
    cv.msg(M.HELLO, P.version + 9, 0);
    const ev = await cv.expect(M.ERROR);
    check('a wrong HELLO version gets ERROR VERSION', ev[1], E.VERSION);
    cv.close();

    /* ---- NETPLAN 2.1: PING is answered ahead of everything, seat or no
       seat -- a PONG must never wait behind the advance gate ----------- */
    const cp = await new Ws().connect(PORT);
    cp.msg(M.PING, U32(0xABCD1234));
    check('an UNSEATED connection\'s PING comes back as PONG, tag verbatim',
          (await cp.expect(M.PONG)).readUInt32LE(1), 0xABCD1234);
    cp.close();

    /* ---- 100 lockstep passes, byte order checked -------------------- */
    c0.msg(M.READY, U32(0));
    c1.msg(M.READY, U32(0));
    let pass = 0, ok = 0;
    for (let i = 0; i < 100; i++){
      const b0 = (i * 3 + 1) & 0x3F, b1 = (i * 7 + 2) & 0x3F;
      c0.msg(M.INPUT, U32(pass), b0);
      c1.msg(M.INPUT, U32(pass), b1);
      const p0 = rdPass(await c0.expect(M.PASS));
      const p1 = rdPass(await c1.expect(M.PASS));
      if (p0.pass === pass && p1.pass === pass &&
          JSON.stringify(p0.dirs) === JSON.stringify([b0, b1]) &&
          JSON.stringify(p1.dirs) === JSON.stringify([b0, b1])) ok++;
      pass++;
    }
    check('100 passes relay both bytes to both clients, in seat order and in step',
          ok, 100);
    c0.msg(M.PING, U32(42));
    check('a seated PING mid-session is answered at once, loop untouched',
          (await c0.expect(M.PONG)).readUInt32LE(1), 42);

    /* ---- pure lockstep: a missing input HOLDS the loop --------------- */
    c0.msg(M.INPUT, U32(pass), 0x11);
    await c0.silent(300);
    checkTrue('with one input missing the loop holds (no PASS inside 300ms)', true);
    c1.msg(M.INPUT, U32(pass), 0x22);
    const heldMsg = await c0.expect(M.PASS);
    const held = rdPass(heldMsg);
    check('...and releases the moment it arrives', [held.pass, held.dirs], [pass, [0x11, 0x22]]);
    /* NETPLAN 2.2: the trailing per-seat WAIT bytes (4 ms units) -- the
       early seat waited the ~300 ms hold, the late one next to nothing */
    const rdWait = m => Array.from(m.subarray(6 + m[5], 6 + 2 * m[5]));
    checkTrue('PASS carries per-seat WAIT bytes: the early seat ~300 ms, the late one ~0',
              heldMsg.length === 6 + 2 * held.n &&
              rdWait(heldMsg)[0] >= 50 && rdWait(heldMsg)[1] <= 12,
              'waits ' + rdWait(heldMsg));
    await c1.expect(M.PASS); pass++;

    /* a stale duplicate (a tag from before a resync) is ignored, not a breach */
    c0.msg(M.INPUT, U32(pass - 2), 0x3F);
    c0.msg(M.INPUT, U32(pass), 7); c1.msg(M.INPUT, U32(pass), 8);
    const ps = rdPass(await c0.expect(M.PASS));
    check('a STALE input tag is ignored and the loop runs on',
          [ps.pass, ps.dirs], [pass, [7, 8]]);
    await c1.expect(M.PASS); pass++;

    /* ---- fingerprints: agreement is silent --------------------------- */
    c0.msg(M.FP, U32(pass - 1), U32(0xDEAD1234));
    c1.msg(M.FP, U32(pass - 1), U32(0xDEAD1234));
    await c0.silent(250); await c1.silent(50);
    checkTrue('matching fingerprints pass without comment', true);

    /* ---- a desync: minority notified, resynced via snapshot ---------- */
    c0.msg(M.FP, U32(pass - 1), U32(0xAAAA0001));
    c1.msg(M.FP, U32(pass - 1), U32(0xBBBB0002));
    const dm = await c1.expect(M.DESYNC);
    check('the tied vote goes to the LOWEST seat: seat 1 gets DESYNC',
          dm.readUInt32LE(1), pass - 1);
    await c0.expect(M.SNAPREQ);
    const resyncJson = Buffer.from(JSON.stringify({ v: 1, note: 'resync' }));
    c0.msg(M.SNAP, U32(pass), resyncJson);
    const sn = await c1.expect(M.SNAP);
    check('...the majority client is asked, and its snapshot arrives verbatim',
          [sn.readUInt32LE(1), sn.subarray(5).toString()],
          [pass, resyncJson.toString()]);
    c1.msg(M.READY, U32(pass));
    c0.msg(M.INPUT, U32(pass), 5); c1.msg(M.INPUT, U32(pass), 6);
    const pr = rdPass(await c0.expect(M.PASS));
    check('...and the loop resumes after the resynced READY', [pr.pass, pr.dirs], [pass, [5, 6]]);
    await c1.expect(M.PASS); pass++;

    /* ---- FULL -------------------------------------------------------- */
    const c2 = await new Ws().connect(PORT);
    c2.msg(M.HELLO, P.version, 0);
    const e2 = await c2.expect(M.ERROR);
    check('a third client is refused: ERROR FULL (seats=2)', e2[1], E.FULL);
    c2.close();

    /* ---- a disconnect frees the seat and the loop substitutes 0 ------ */
    c1.close();
    await sleep(300);                     // let the server notice
    c0.msg(M.INPUT, U32(pass), 0x2A);
    const pd = rdPass(await c0.expect(M.PASS));
    check('after seat 1 disconnects its byte is substituted 0x00',
          [pd.pass, pd.dirs], [pass, [0x2A, 0]]);
    pass++;

    /* ---- late join: WELCOME(SNAPSHOT), 20 KB forwarded verbatim ------ */
    const c3 = await new Ws().connect(PORT);
    c3.msg(M.HELLO, P.version, 2);      // ignored: his character is in the snapshot
    const w3 = rdWelcome(await c3.expect(M.WELCOME));
    check('a late joiner takes the freed seat in SNAPSHOT mode at the live pass',
          [w3.seat, w3.mode, w3.pass], [1, MODE.SNAPSHOT, pass]);
    check('...same session, same seed', w3.seed, w0.seed);
    check('a nameless HELLO is tolerated, and seat reuse OVERWRITES the leaver\'s name',
          (await c3.expect(M.NAMES)).subarray(1).toString(),
          'ANTHONY ' + ' '.repeat(24));
    await c0.expect(M.SNAPREQ);
    const big = { v: 1, blob: 'x'.repeat(20000), pass };
    const bigJson = Buffer.from(JSON.stringify(big));
    c0.msg(M.SNAP, U32(pass), bigJson);
    const s3 = await c3.expect(M.SNAP, 5000);
    const gotJson = s3.subarray(5);
    check('a 20 KB snapshot crosses the relay intact (16-bit frame path)',
          [s3.readUInt32LE(1), gotJson.length,
           crypto.createHash('sha1').update(gotJson).digest('hex')],
          [pass, bigJson.length,
           crypto.createHash('sha1').update(bigJson).digest('hex')]);
    c3.msg(M.READY, U32(pass));
    for (let i = 0; i < 5; i++){
      c0.msg(M.INPUT, U32(pass), 1); c3.msg(M.INPUT, U32(pass), 2);
      const pp = rdPass(await c0.expect(M.PASS));
      check('post-join pass ' + i + ' needs BOTH inputs again',
            [pp.pass, pp.dirs], [pass, [1, 2]]);
      await c3.expect(M.PASS); pass++;
    }

    /* ---- orphaned session resets ------------------------------------- */
    c0.close(); c3.close();
    await sleep(300);
    const c4 = await new Ws().connect(PORT);
    c4.msg(M.HELLO, P.version, 1);
    const w4 = rdWelcome(await c4.expect(M.WELCOME));
    check('with every seat emptied the session reset: next client is FRESH at pass 0',
          [w4.seat, w4.mode, w4.pass], [0, MODE.FRESH, 0]);
    check('...and the character table reset with it',
          Array.from((await c4.expect(M.CHARS)).subarray(1)), [1, 255, 255, 255]);
    check('...and the name table too',
          (await c4.expect(M.NAMES)).subarray(1).toString(), ' '.repeat(32));
    c4.close();
  } finally {
    proc.kill();
  }

  console.log(`\n${checks - failures}/${checks} relay checks passed`);
  process.exit(failures ? 1 : 0);
}

main().catch(e => { console.error('ABORT: ' + (e.stack || e)); process.exit(1); });
